Configure mtwifi script without additional arguments & Add sleep for stop command

diff --git a/mt7697wifi-driver/scripts/mtwifi b/mt7697wifi-driver/scripts/mtwifi
--- a/mt7697wifi-driver/scripts/mtwifi
+++ b/mt7697wifi-driver/scripts/mtwifi
@@ -69,8 +69,14 @@ mt_wifi_stop() {
 
     lsmod | grep mt7697core >/dev/null
     if [ $? -eq 0 ]; then
-        modprobe -r mt7697core || exit 127
-        echo "Removed MT7697 WiFi core"; exit 127
+        modprobe -r mt7697core
+        sleep 1
+        # Check the return status of the command
+        if [ $? -eq 0 ]; then
+            echo "Removed MT7697 WiFi core"
+        else
+            echo "Faield to Removed MT7697 WiFi core"
+        fi
     fi
 }
 
@@ -78,16 +84,20 @@ mt_wifi_stop() {
 case "$1" in
     start)
         # ./mtwifi start uart 0
-        mt_wifi_start $2 $3
+        # mt_wifi_start $2 $3
+        mt_wifi_start "uart" 0
         ;;
     stop)
         # ./mtwifi stop 0
-        mt_wifi_stop $2
+        # mt_wifi_stop $2
+        mt_wifi_stop 0
         ;;
     restart)
         # ./mtwifi restart uart 0
-        mt_wifi_stop $2
-        mt_wifi_start $2 $3
+        # mt_wifi_stop $2
+        # mt_wifi_start $2 $3
+        mt_wifi_stop 0
+        mt_wifi_start "uart" 0
         ;;
     *)
         exit 1
